### ISSUE TITLE
[QUEST] tianji of the ox

### ISSUE THREAD

**Issue by hugyy59** [Blackhandpl/bugtracker#380] opened 2021-05-04 09:56 UTC
1. (Name of Quest, Spell, object etc.): tianji of the ox
2. (ID): 41945
3. (Description): Mission not appearing on Class Hall Report. It's a monk quest for the campaign.
4. (Wowhead link): https://www.wowhead.com/quest=41945/tianji-of-the-ox

**Comment by grzewal1** [comment] 2021-05-04 19:48
Duplicate of #292

**Closed as completed by grzewal1** 2021-05-04 19:48 UTC
