### ISSUE TITLE
reinforcements

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1688] opened 2018-06-12 20:51 UTC
Description:  quest item nie działa na koboldy nic się  nie dzieje

Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=26066/reinforcements

**Comment by grzewal1** [comment] 2020-12-16 13:22
Duplicate of #1204

**Closed by grzewal1** 2020-12-16 13:22 UTC
Labels: 7.x, Cataclysm, Item, Npc, Quest
