### ISSUE TITLE
were-here-to-do-one-thing-maybe-two

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1690] opened 2018-06-12 21:24 UTC
Description: questa nieda  się oddac npc ma focha
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two

**Comment by grzewal1** [comment] 2020-12-14 16:50
Duplicate of #1238

**Closed by grzewal1** 2020-12-14 16:50 UTC
Labels: 7.x, Cataclysm, Npc, Quest
